S14wc
ImagingDataCommons/IDC-API pull request #5
Opened 2020-10-02 20:07 UTC by bcli4d

2020-10-05 02:48 UTC, s-paquette reviewed
Note, it's also saying this is out of date with master and needs to do a pull.

2020-10-05 02:48 UTC, s-paquette commented on Dockerfile
This won't work; the folder is api not apiv1. So /app/api: and then below, api:app (unless you've changed it to apiv1 but it doesn't appear to be the case).

2020-10-05 02:49 UTC, s-paquette requested changes
Need to fix the apiv1 bit.

2020-10-06 03:24 UTC, bcli4d commented
Done.

On Sun, Oct 4, 2020 at 7:49 PM S. Paquette <notifications@github.com> wrote:

> *@s-paquette* requested changes on this pull request.
>
> Need to fix the apiv1 bit.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ImagingDataCommons/IDC-API/pull/5#pullrequestreview-501696066>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGK2VI7W4JS3NAITNRVRVITSJEX3HANCNFSM4SCDLIIA>
> .
>

2020-10-06 08:54 UTC, s-paquette approved these changes

2020-10-06 08:54 UTC, merged